### ISSUE TITLE
Potential Jekyll themes

### ISSUE THREAD

**Issue by michael-collins** [open-curriculum/program-hub#2]
- https://phlow.github.io/feeling-responsive/blog/
- https://github.com/chrisanthropic/slim-pickins-jekyll-theme
- **https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/**

**Comment by zanesensenig** [comment]
Phlow is a nice traditional blog. Minimal Mistakes could work as well. 

I'll post any links that I find.

**Comment by michael-collins** [comment]
I have jekyll-foundation installed now. Just working on getting the foundation source files into scope when it compiles. Some url problem I can't figure out.

**Comment by michael-collins** [comment]
This is what is in the repo now. Pretty bare bones: http://foundationjekyll.com
