### ISSUE TITLE
Search is not functional

### ISSUE THREAD

**Issue by zanesensenig** [open-curriculum/program-hub#27]

**Comment by mmilutinovic013** [comment]
Looking into this. If anyone has any other thoughts -- let me know! 
http://jekyll.tips/jekyll-casts/jekyll-search-using-lunr-js/

**Comment by zanesensenig** [comment]
I think that is perfect!

**Comment by mmilutinovic013** [comment]
@michael-collins do we need this still? You indicated this site does not need a search

**Comment by mmilutinovic013** [comment]
Delete search

**Comment by mmilutinovic013** [comment]
JK comment out the icon
