### ISSUE TITLE
Curriculum view

### ISSUE THREAD

**Issue by michael-collins** [open-curriculum/program-hub#30]
The curriculum tab needs to list the dmd specific courses, and then some from Comm, IST, and SoVA as well. To start, we'll need some formatting that looks like this:
### Course Number

**Course Title**
Course description. blah blah blah

**Comment by michael-collins** [comment]
This can probably be the same content as the pathways view, but with a different jekyll template.

**Comment by michael-collins** [comment]
@zanesensenig Would you be able to do a mockup for this?

**Comment by zanesensenig** [comment]
I won't be able to mock this up between now and Thursday. I am happy to create filler content using the structure above. However, I'm thinking we can use an accordion for this? Label each toggle with a discipline, and list the courses when the accordion item is clicked.

**Comment by michael-collins** [comment]
@zanesensenig that will work just fine.

**Comment by michael-collins** [comment]
I think doing it in html is fine for now. At some point, we want to have it set up more like a collection, where the course details are front matter variables, and then they get printed in the html. Makes it cleaner to update. We'll cross that bridge at some point.
