### ISSUE TITLE
pathways link is broken on production

### ISSUE THREAD

**Issue by michael-collins** [open-curriculum/program-hub#47]
@mmilutinovic1313 Pathways button on front page is a bad link. Can you fix this and re-upload to server?

**Comment by mmilutinovic013** [comment]
Yes, do you know where it is pointing to just to make sure I have the most update code

**Comment by michael-collins** [comment]
It has a `/program-hub` in the url path.

**Comment by mmilutinovic013** [comment]
Noted - I will try and update this ASAP today / tomorrow

**Comment by mmilutinovic013** [comment]
Fixed
