### ISSUE TITLE
create a collection for courses on pathways tab

### ISSUE THREAD

**Issue by michael-collins** [open-curriculum/program-hub#49]
To be able to update the website faster, we need to structure it a bit more. Jekyll is great because it allows us to make things modular.

Right now, there is a ton of copy and paste of HTML code that happens, which is too hard to quickly update. I want to change the courses listed on the **Pathways tab** on the website by adding or removing a md file in a folder called ```courses```.

This means, we need a collection for courses. Changes include:

- [x] 1. collection entry in ```config.yml``` file to enable this functionality
- [x] 2. ```/courses/coursename.md``` (ex. dmd100.md)
  - Front matter variables
    - layout: pathwaycourse
    - title:
    - description:
    - bulletin-link:
    - pathway-list: (there should be multiple entries here, a course can be in two different pathways at once)
    - I might be missing one, but I think this is it.
- [x] 3. ```/program/index.html```
  - loops that print out all entries for ```pathwaycourse``` in lists of courses on the pathways tab. It knows this from the front matter settings on the course md files.
  - loop should print in alphabetical order. There is a shorthand method to do this in the loop statement.
- [x] 4. ```/_layouts/pathwaycourse.html```
  - Move the repeatable accordion html into here (probably the the ```<li>``` html, but not the ```<ul>```. The coursename.md frontmatter variables will get applied to this layout before moving to be rendered at the ```program/index.html``` page. As noted above, write this layout as a variable in the frontmatter on the ```/collection/coursename.md```
- [x] 5. We can either manually create the pathway list titles, or you can make a loop that finds all the pathwaycourse variables.
  - Current Pathway names (which will change over time) include: Generalist, Video Production, Digital Design, Interactive Media Developer, Media for Civic Engagement
  - Again, it would be great if adding another variable somewhere could change these lists instead of altering the html.

**Comment by mmilutinovic013** [comment]
This is currently my primary task. Just wanted to ping you here to let you know this is in progress

**Comment by michael-collins** [comment]
The pathway collapse fields all trigger together. We probably need to inject create unique IDs for the fields and triggers.

**Comment by mmilutinovic013** [comment]
Yep yep - I noticed that too. can we add something in the `href` to make it unique id?

**Comment by mmilutinovic013** [comment]
Last pull request fixes this issue although we can fix up some styling before we move this to prod if desired.
