### ISSUE TITLE
Create a faculty collection

### ISSUE THREAD

**Issue by michael-collins** [open-curriculum/program-hub#55]
We need the "meet the faculty" tab on the about page to be driven from markdown files as well to make it easier to add people. This one should be pretty easy, though we do need to make sure that the lead faculty are always at the top of the list.

faculty/
- faculty-NAME.md
  - frontmatter
    - name:
    - title(s):
    - bio:
    - image-url:
    - lead-faculty: yes/no
    - published:

_layouts/faculty-profile.html
  - add the html stuff here.

about/index.html
  - print out the faculty members.

**Comment by mmilutinovic013** [comment]
Okay, yes lead faculty could be sorted by yes or no - so this would be pretty simple to do. I'll be working tonight and in all day tomorrow on this / the other issue. I've been out most of the week finishing up some schoolwork

**Comment by mmilutinovic013** [comment]
This has been added
